name: Deploy GitHub Pages (aggregate concepts)

on:
  push:
    branches:
      - main
      - concept-editor
      - concept-selection
      - concept-creation
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Fetch other concept branches
        run: |
          git fetch origin concept-editor:concept-editor || true
          git fetch origin concept-selection:concept-selection || true
          git fetch origin concept-creation:concept-creation || true

      - name: Prepare site dirs
        run: |
          rm -rf site
          mkdir -p site/expansion/concept1 site/expansion/concept2 site/creation

      - name: Copy concept-editor → expansion/concept1 (overlay wizard)
        run: |
          git checkout concept-editor
          rsync -a --delete --exclude '.git' ./ site/expansion/concept1/

      - name: Copy concept-selection → expansion/concept2 (sidebar panel)
        run: |
          git checkout concept-selection
          rsync -a --delete --exclude '.git' ./ site/expansion/concept2/

      - name: Copy concept-creation → creation (source-based)
        run: |
          git checkout concept-creation
          rsync -a --delete --exclude '.git' ./ site/creation/

      - name: Aggregate landing index
        run: |
          cat > site/index.html <<'HTML'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1"/>
            <title>VE Concepts — Demo Hub</title>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; margin: 0; padding: 40px 20px; }
              .container { max-width: 820px; margin: 0 auto; }
              h1 { font-size: 1.8rem; font-weight: 600; margin: 0 0 16px; }
              h2 { font-size: 1.2rem; margin: 24px 0 8px; }
              ul { padding-left: 18px; }
              li { margin: 8px 0; }
              a { color: #0645ad; text-decoration: none; }
              a:hover { text-decoration: underline; }
              .note { color: #555; }
              .group { margin: 28px 0; }
  .card { border: 1px solid #eaecf0; border-radius: 6px; padding: 14px 16px; margin: 12px 0; }
  .card h3 { margin: 0 0 6px; font-size: 1.05rem; }
  .card p { margin: 0 0 8px; color: #555; }
  .links { display: flex; gap: 12px; flex-wrap: wrap; }
  .badge { display:inline-block; font-size: 12px; padding: 2px 8px; border:1px solid #c8ccd1; border-radius: 999px; color:#555; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>VisualEditor Concepts — Demo Hub</h1>
              <p class="lead">All concepts are published from their branches into subfolders here.</p>

              <div class="group">
                <h2>Section Expansion</h2>
                <div class="card">
                  <h3>Concept 1 — Overlay Wizard <span class="badge">Guided flow</span></h3>
                  <p>A step-by-step overlay that helps pick a section, add sources, and review before insertion.</p>
                  <div class="links">
                    <a href="expansion/concept1/articles-concept1.html">Browse articles</a>
                    <a href="expansion/concept1/katie-bouman.html">Open example (Katie Bouman)</a>
                  </div>
                </div>
                <div class="card">
                  <h3>Concept 2 — Sidebar Panel <span class="badge">Inline suggestions</span></h3>
                  <p>A right-side panel with suggestions; on mobile it opens as a bottom drawer.</p>
                  <div class="links">
                    <a href="expansion/concept2/articles-concept2.html">Browse articles</a>
                    <a href="expansion/concept2/katie-bouman.html">Open example (Katie Bouman)</a>
                  </div>
                </div>
              </div>

              <div class="group">
                <h2>Article Creation</h2>
                <div class="card">
                  <h3>Concept A — Source-based split view <span class="badge">Structured</span></h3>
                  <p>Split layout: add sources on the left, compose the draft on the right, with preflight checks.</p>
                  <div class="links">
                    <a href="creation/creation.html">Open concept</a>
                  </div>
                </div>
                <div class="card">
                  <h3>Concept B — Reference chip flow <span class="badge">Lightweight</span></h3>
                  <p>Start with a title and category, then use chips (Introduction, Fact, More, Reference) while drafting.</p>
                  <div class="links">
                    <a href="creation/article-creator.html">Open concept</a>
                  </div>
                </div>
              </div>
            </div>
          </body>
          </html>
          HTML

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
